Fixing Load Balancer Health Check
corelight/terraform-azure-sensor pull request #13
Opened 2024-12-19 19:06 UTC by thathaneydude

# Description

Fixing load balancer health check by including the monitoring subnet info in the sensor configuration to ensure LB probes coming into the monitoring NIC also go out the monitoring NIC.

## Type of change
- [X] Bug Fix

# How Has This Been Tested?

Tested thoroughly locally

2024-12-20 05:56 UTC, retr0h commented
We should prob update the diagram to reflect these changes.

2024-12-20 16:10 UTC, thathaneydude commented
> We should prob update the diagram to reflect these changes.

Good call - I'll get a new diagram pushed to this branch

2025-01-06 16:52 UTC, simdugas requested changes
Looks good overall, a couple nits, and a change request.

2025-01-06 16:52 UTC, simdugas commented on data.tf
> +  monitoring_subnet_resource_id_slice = split("/", var.monitoring_subnet_id)
nit: consider creating locals for the slice components we use instead of exposing the slice variable. Would be nice to resolve all of these in one place.

2025-01-06 16:52 UTC, simdugas commented on sensor_config.tf
> +  sensor_health_check_http_port                = "41080"
I see the literal value `41080` across the module. Did we mean to remove these now that a variable is available?

2025-01-06 16:52 UTC, simdugas commented on variables.tf
> +  description = "Name of the internal load balancer monitoring backend pool frontend ip configuration"
variable name says management, but description says monitoring?

2025-01-06 18:12 UTC, simdugas approved these changes
Nice work, lgtm!

2025-01-06 18:26 UTC, merged